### ISSUE TITLE
Valid numbers are displayed red

### ISSUE THREAD

**Issue by dominik-boehm** [fedeztk/sku#1]
![grafik](https://user-images.githubusercontent.com/107146541/172695162-70ec87bf-ccd1-43d4-baca-be782abd6346.png)
1 and 8 can be switched

**Comment by dominik-boehm** [comment]
nice game

**Comment by fedeztk** [comment]
Thanks for the report, it is obviously an unexpected behavior. I'll fix it soon.

**Comment by fedeztk** [comment]
After some investigations I find out it is due to how the sudoku backend is implemented: it does not generate a minimal sudoku (that has one and only one solution); moreover it only generate one solution and not all of them. This explain that error.

I do not see many solution other than implementing the backend myself or switching to a more functional one.

**Comment by fedeztk** [comment]
The PR #2 finally solves this issue. I implemented the sudoku engine myself. 
Please, feel free to reopen if something like this still happen.
